import { NextResponse } from "next/server"
import * as XLSX from "xlsx"

export async function GET() {
  // Create workbook
  const wb = XLSX.utils.book_new()

  // Create survey sheet
  const surveyData = [
    [
      "type",
      "name",
      "label",
      "required",
      "appearance",
      "relevant",
      "constraint",
      "constraint_message",
      "default",
      "calculation",
      "style",
    ],
    [
      "begin_group",
      "consent_group",
      "CONSENT FOR CRIMINAL RISK ASSESSMENT AND RELEASE OF INFORMATION",
      "",
      "field-list",
      "",
      "",
      "",
      "",
      "",
      "banner:true;color:blue",
    ],
    [
      "note",
      "consent_note",
      'As a person who has, or may have, care, custody, control or charge of a child in receipt of services under The Child and Family Services Act, I authorize the Criminal Risk Assessment Unit of Manitoba Families\' Child Protection Branch ("CRAU") to conduct enquiries of the Winnipeg Police Service (WPS), the RCMP and other law enforcement agencies necessary to assess the risk that l may endanger the life, health or emotional wellbeing of a child.',
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "color:darkblue",
    ],
    ["date", "consent_date", "Date:", "yes", "", "", "", "Please enter the date", "", "", "color:blue"],
    [
      "text",
      "signature",
      "Signature of person being assessed:",
      "yes",
      "",
      "",
      "",
      "Please enter the signature",
      "",
      "",
      "color:blue",
    ],
    ["text", "witness", "Unconsented Witness (if consenting):", "", "", "", "", "", "", "", "color:blue"],
    ["end_group", "", "", "", "", "", "", "", "", "", ""],

    [
      "begin_group",
      "personal_info",
      "PERSONAL INFORMATION - PLEASE PRINT CLEARLY",
      "",
      "field-list",
      "",
      "",
      "",
      "",
      "",
      "banner:true;color:green",
    ],
    ["text", "first_name", "1. FIRST NAME:", "yes", "", "", "", "Please enter first name", "", "", "color:green"],
    ["text", "second_name", "2. SECOND NAME:", "", "", "", "", "", "", "", "color:green"],
    ["text", "last_name", "3. LAST NAME:", "yes", "", "", "", "Please enter last name", "", "", "color:green"],
    [
      "date",
      "date_of_birth",
      "4. DATE OF BIRTH:",
      "yes",
      "",
      "",
      "",
      "Please enter date of birth",
      "",
      "",
      "color:green",
    ],
    ["select_one gender", "gender", "5. GENDER:", "yes", "", "", "", "Please select gender", "", "", "color:green"],
    ["text", "other_last_names", "6. OTHER LAST NAMES USED:", "", "", "", "", "", "", "", "color:green"],
    ["text", "other_first_names", "7. OTHER FIRST NAMES USED/ALSO GOES BY:", "", "", "", "", "", "", "", "color:green"],
    [
      "text",
      "current_address",
      "8. CURRENT ADDRESS (include postal code):",
      "yes",
      "",
      "",
      "",
      "Please enter current address",
      "",
      "",
      "color:green",
    ],
    [
      "text",
      "current_phone",
      "9. CURRENT PH#s:",
      "yes",
      "",
      "",
      "",
      "Please enter phone number",
      "",
      "",
      "color:green",
    ],
    ["text", "birth_place", "10. City/Province or Country of Birth:", "", "", "", "", "", "", "", "color:green"],
    ["end_group", "", "", "", "", "", "", "", "", "", ""],

    [
      "begin_group",
      "identification",
      "IDENTIFICATION VERIFICATION",
      "",
      "field-list",
      "",
      "",
      "",
      "",
      "",
      "banner:true;color:purple",
    ],
    [
      "note",
      "id_note",
      "PLEASE NOTE: Subject's name must be identified with TWO PIECES OF IDENTIFICATION (MB D/L & photo ID is preferable):",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "color:purple",
    ],
    [
      "select_multiple id_types",
      "id_types",
      "ID Types:",
      "yes",
      "",
      "",
      "",
      "Please select at least two ID types",
      "",
      "",
      "color:purple",
    ],
    [
      "text",
      "drivers_license",
      "MB Driver's License with Photo - licence number (section 4d on licence):",
      "",
      "",
      "${id_types} contains 'drivers_license'",
      "",
      "",
      "",
      "",
      "color:purple",
    ],
    [
      "text",
      "other_id_specify",
      "Other (specify ID):",
      "",
      "",
      "${id_types} contains 'other'",
      "",
      "",
      "",
      "",
      "color:purple",
    ],
    ["end_group", "", "", "", "", "", "", "", "", "", ""],

    [
      "begin_group",
      "agency_info",
      "AGENCY INFORMATION",
      "",
      "field-list",
      "",
      "",
      "",
      "",
      "",
      "banner:true;color:orange",
    ],
    [
      "text",
      "agency_name",
      "NAME OF AGENCY SUBMITTING REQUEST:",
      "yes",
      "",
      "",
      "",
      "Please enter agency name",
      "",
      "",
      "color:orange",
    ],
    [
      "select_one reason",
      "reason",
      "REASON FOR RISK ASSESSMENT:",
      "yes",
      "",
      "",
      "",
      "Please select a reason",
      "",
      "",
      "color:orange",
    ],
    [
      "text",
      "assigned_worker",
      "ASSIGNED WORKER:",
      "yes",
      "",
      "",
      "",
      "Please enter assigned worker",
      "",
      "",
      "color:orange",
    ],
    [
      "date",
      "last_assessment_date",
      "DATE OF LAST CRIMINAL RISK ASSESSMENT (if known):",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "color:orange",
    ],
    [
      "text",
      "submitting_designate",
      "SUBMITTING DESIGNATE:",
      "yes",
      "",
      "",
      "",
      "Please enter submitting designate",
      "",
      "",
      "color:orange",
    ],
    [
      "text",
      "designate_phone",
      "DESIGNATE PH#:",
      "yes",
      "",
      "",
      "",
      "Please enter designate phone",
      "",
      "",
      "color:orange",
    ],
    [
      "text",
      "designate_email",
      "DESIGNATE EMAIL#:",
      "yes",
      "",
      "",
      "",
      "Please enter designate email",
      "",
      "",
      "color:orange",
    ],
    ["text", "designate_fax", "DESIGNATE FAX#:", "", "", "", "", "", "", "", "color:orange"],
    ["date", "request_date", "REQUEST DATE:", "yes", "", "", "", "Please enter request date", "", "", "color:orange"],
    ["end_group", "", "", "", "", "", "", "", "", "", ""],

    ["begin_group", "disclaimer", "DISCLAIMER", "", "", "", "", "", "", "", "banner:true;color:red"],
    [
      "note",
      "disclaimer_note",
      "NOTE: The assessment completed by the Criminal Risk Assessment Unit of the Department of Families Child Protection Branch does not replace a criminal records check.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "color:red",
    ],
    ["end_group", "", "", "", "", "", "", "", "", "", ""],
  ]

  // Create choices sheet
  const choicesData = [
    ["list_name", "name", "label"],
    ["gender", "male", "MALE"],
    ["gender", "female", "FEMALE"],
    ["gender", "other", "OTHER"],

    ["id_types", "birth_certificate", "Birth Certificate"],
    ["id_types", "social_insurance", "Social Insurance Card"],
    ["id_types", "health_card", "Manitoba Health Card"],
    ["id_types", "treaty_card", "Treaty Card"],
    ["id_types", "drivers_license", "MB Driver's License with Photo"],
    ["id_types", "other", "Other"],

    ["reason", "child_protection", "Child Protection Concerns"],
    ["reason", "place_of_safety", "Place of Safety"],
    ["reason", "kinship", "Kinship or Customary Care Agreement"],
  ]

  // Create settings sheet
  const settingsData = [
    ["form_title", "form_id", "version", "default_language", "style"],
    ["Criminal Risk Assessment Request", "criminal_risk_assessment", "1.0", "English", "theme-grid"],
  ]

  // Add sheets to workbook
  const surveySheet = XLSX.utils.aoa_to_sheet(surveyData)
  const choicesSheet = XLSX.utils.aoa_to_sheet(choicesData)
  const settingsSheet = XLSX.utils.aoa_to_sheet(settingsData)

  XLSX.utils.book_append_sheet(wb, surveySheet, "survey")
  XLSX.utils.book_append_sheet(wb, choicesSheet, "choices")
  XLSX.utils.book_append_sheet(wb, settingsSheet, "settings")

  // Write to buffer
  const buf = XLSX.write(wb, { type: "buffer", bookType: "xlsx" })

  // Return as downloadable file
  return new NextResponse(buf, {
    headers: {
      "Content-Disposition": 'attachment; filename="colorful_criminal_risk_assessment.xlsx"',
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    },
  })
}
